package com.paxees_daily_smart.paxees_news_app.Utilities;

public class Config {
    public static final String EMPTY_STRING = "";
    public static final String API_KEY = "AIzaSyB4DunOLzliLkj_UHjZkwLcUwjmLhYDLjM";
    public static final String BASE_URL = "https://www.bharatshorts.in/api/";
    public static final String PROFILE_IMAGE_URL = BASE_URL + "profiles/";
    public static final String NEWS_IMAGE_URL = "https://www.bharatshorts.in/admin/postimages/";
    public static final String UPLOAD_POST_VIDEO_URL = "https://www.bharatshorts.in/admin/upload.php";
    public static final String SPLASH_IMAGE_URL = BASE_URL + "splash/";
    public static final String TOUR_SCREEN_URL = BASE_URL + "get_splash";
    public static final String DISTRICT_LIST = BASE_URL + "district";
    public static final String STATES_LIST = BASE_URL + "states";
    public static final String VERIFY_OTP = BASE_URL + "verify_otp";
    public static final String CATEGORIES = BASE_URL + "categories";
    public static final String NEWS_BASED_ON_CATEGORIES = BASE_URL + "newsbasedoncategories";
    public static final String TRENDING_NEWS = BASE_URL + "trending_news";
    public static final String NEWS_DETAILS = BASE_URL + "news_details";
    public static final String GET_PROFILE_DETAILS = BASE_URL + "get_profile";
    public static final String UPDATE_PROFILE_DETAILS = BASE_URL + "update_profile";
    public static final String POST_NEWS = BASE_URL + "news_post";
    public static final String POST_NEWS_VIDEO = BASE_URL + "image_upload.php";
    public static final String GET_COMMENTS = BASE_URL + "comments";
    public static final String POST_COMMENTS = BASE_URL + "post_comments";
    public static final String LIKE_COMMENTS = BASE_URL + "like_comments";
    public static final String UNLIKE_COMMENTS = BASE_URL + "unlike_comments";
    public static final String POST_SUB_COMMENTS = BASE_URL + "post_sub_comments";
    public static final String ADD_FAVOURITES = BASE_URL + "add_favorites";
    public static final String REMOVE_FAVOURITES = BASE_URL + "remove_favorites";
    public static final String LIST_OF_FAVOURITES = BASE_URL + "favorites_list";
    public static final String GET_REPORTER_POSTS = BASE_URL + "news_based_on_reporter";
    public static final String DELETE_REPORTER_POSTS = BASE_URL + "news_delete";
    public static final String ADD_FOLLOWER = BASE_URL + "add_followers";
    public static final String REMOVE_FOLLOWER = BASE_URL + "remove_followers";
    public static final String GET_FOLLOWERS_LIST = BASE_URL + "get_followers";
    public static final String GET_FOLLOWING_LIST = BASE_URL + "get_following";
    public static final String POST_SHARE_COUNT = BASE_URL + "share_count";
    public static final String DEVICE_REG = BASE_URL + "device_reg";
    public static final String PAGES_ABOUT_US = BASE_URL + "pages";
    public static final String CONTACT_US = BASE_URL + "contact_us";
    public static final String ADS_SETTINGS = BASE_URL + "ads";
}
